### ISSUE TITLE
Can't discard

### ISSUE THREAD

**Issue by PoussinW** [guladam/deck_builder_tutorial#1]
In the player_handler.gd

you'll get soft lock if you don't have any cards left in your hands.

" Tween (bound to /root/Battle/PlayerHandler): started with no Tweeners."

**Comment by guladam** [comment]
Hey, this is fixed in the YouTube video at:

https://youtu.be/yiGD36RGdzQ?si=Q0l_DiAOWnpsLH3c&t=166

**Comment by PoussinW** [comment]
Hey, thanks for the answer!

I fixed it this way, I don't know if that's better or worse than the one you showed, but again, thanks for the answer :>
![image](https://github.com/guladam/deck_builder_tutorial/assets/59364053/1ed9e4f0-4cba-44cb-9c9a-72b769c4d442)

**Comment by guladam** [comment]
It is really similar actually!

Thanks for pointing it out :)
