### ISSUE TITLE
Card not snapping back to hand when released if I do absolutely no movement with mouse

### ISSUE THREAD

**Issue by RafaMenezes** [guladam/deck_builder_tutorial#11]
If I release the card but do absolutely no movement with my mouse after, since it receives no input, the card stays released even where it shouldn't, and it only snaps back to hand once I touch my mouse so that it moves. I believe the reason for this is that it goes back to BASE state in this:

func on_input(_event: InputEvent) -> void:
	if played:
		return
	
	transition_requested.emit(self, CardState.State.BASE)
	
So if I let go of the left click but don't move at all my mouse, the card stays where I left it. Only once I touch the mouse, it goes back to the hand as intended.

**Comment by guladam** [comment]
Hey, what operating system you're using? I can't reproduce this on Windows. When I release it, no matter what I do, it goes back to the base state.

**Comment by RafaMenezes** [comment]
Hi Adam, thanks for getting back to me.
I'm using a MacOS Sonoma 14.5.

Whenever I have some time off I will try to check again if I did something
wrong, but as far as I recall I followed this part exactly as in the video.

**Comment by guladam** [comment]
It probably has to do something with how different OSes handle input a bit differently. I don't have a Mac, but I'll try to reproduce it on Linux. Thanks for your input!

**Comment by RafaMenezes** [comment]
Thanks a lot for putting the time. Awesome tutorial, hope to have my game
ready and actually release in a couple years, this tutorial helped me a lot.

Just saw the vote for the next series, can't believe tower defense is gonna
win. You HAVE to make an autobattler one 😭 jokes aside, anything will be
valuable content, keep it up and looking forward!

**Comment by guladam** [comment]
I was able to reproduce it on Linux!
Working on a fix right now. :)

Would love to play your game one day, good luck with creating it.

Even if the TD game wins, I can do the autobattler next 👀

**Comment by RafaMenezes** [comment]
Awesome! Thank you very much!

**Comment by RafaMenezes** [comment]
Just a quick comment, for it to work in my case, where I reparent the card after playing because I snap it to a position on the board (unlike StS where the card vanishes) I had to keep if played: return also in post_enter().

**Comment by guladam** [comment]
Great! Thanks for sharing.
