### ISSUE TITLE
Bug with treasure room and relics. -Bug

### ISSUE THREAD

**Issue by BrokedArrer** [guladam/deck_builder_tutorial#13]
one bug that I noticed while testing was that if you already have all of the relics, and get to a treasure room and open the chest, it will crash the game because you already have all the relics and therefore will not actually generate one as a reward.

**Comment by guladam** [comment]
In reality, that would be impossible to do in a commercial game as you want to have way more relics than you amount you can unlock. That said, it's still a good idea to handle this so we'll fix it. Thanks!
