### ISSUE TITLE
Mid-combat bug from the "get_active_enemy_modifiers" function

### ISSUE THREAD

**Issue by oj88z** [guladam/deck_builder_tutorial#14]
![Skjermbilde (517)](https://github.com/guladam/deck_builder_tutorial/assets/147167038/59a79237-1533-429d-9574-d9dad285d641)
![Skjermbilde (518)](https://github.com/guladam/deck_builder_tutorial/assets/147167038/087c5daf-46a8-4433-84f1-f59a7d9d5fa5)

I got this bug when playtesting the game. Unfortunately, I have no idea how to reproduce it. It occured after I killed a bat with a regular "warrior_axe_attack". I'm not sure if the bat had the "Exposed" debuff when it happened eighter, but it seems like it could be related to that?

This happened after completing season 2 episode 12.

This is my first time posting anything, so I just want to say thanks a lot for the continued support of the series :)

**Comment by guladam** [comment]
Did it occur again? I wasn't able to reproduce it unfortunately :(

**Comment by oj88z** [comment]
No. I still have no idea how or why it happened :(

If it happens again or if I learn something new, I'll let you know. At the moment I don't have a clue why it happened. Hopefully it's just an error on my end.
