### ISSUE TITLE
It is possible for enemy conditional skills to be used up between when the Enemy acts and the End of Turn

### ISSUE THREAD

**Issue by mendez-jp** [guladam/deck_builder_tutorial#17]
(This is the first issue I have ever written, so sorry if this is not the right way of doing it)
I implemented a Burn mechanic which deals damage to the enemy at the end of their turn (but thorn damage can do the same thing), and I noticed that if Burn damage caused Crab to go below the threshold needed for the Conditional Action Mega Block, the action will not be used. Stepping through the code (learning how to debug properly), I noticed that the Burn damage ends up triggering update_action (which sets the action to Mega Block), then the end of turn triggers reset_enemy_actions and a new action is assigned, leaving Mega Block "already used" but the action not actually being used.

My, likely incorrect solution, was to add a bool variable for action_performed that gets set to true in enemy_handler._on_enemy_action_completed and then that same variable gets set to false in enemy_handler.reset_enemy_actions the line before we call enemy.update_action()

**Comment by guladam** [comment]
Thanks for submitting the issue, it is a perfectly fine way to do it! :)

I was able to reproduce it quite easily. While your solution works, there is an easier way to fix it. The system itself is fine but I made a mistake in the code.

You can see how I changed it in this commit: https://github.com/guladam/deck_builder_tutorial/commit/0922341c13c93affaefcab638c67c21006508b3f
