### ISSUE TITLE
If you open the deck view before you are attacked by an enemy and you die you cannot get back to the main menu.

### ISSUE THREAD

**Issue by DistinguishedGent** [guladam/deck_builder_tutorial#20]
If the player opens the deck view before they are killed the deck view blocks the menu button. Because the game is now paused, the deck view cannot be closed.

**Comment by guladam** [comment]
Confirmed, I could reproduce it.

2 ways to fix this:
- Change the process mode of the CardPileView root node to *Always*
- Make sure that the battle hides all CardPileViews (Deck, Draw, Discard) when you lose/win a Battle.

I went with the first solution in the commit above.

Thanks for contributing! :)

**Comment by DistinguishedGent** [comment]
Wow, thank you for the quick response! I like the first solution as well.
