### ISSUE TITLE
Confusing staff and drawing cards

### ISSUE THREAD

**Issue by DistinguishedGent** [guladam/deck_builder_tutorial#23]
If you pick up a card from the hand and hold onto it before the hand has finished being drawn, the Confusing Staff will not alter its cost. I believe this is because the card is no longer parented to the hand.

**Comment by guladam** [comment]
Hey, thanks for pointing this out. I fixed this in multiple stacks (you can check the commit):

- card_ui is disabled by default
- there is a new method called enable_hand() which enables all cards in hand (note that it doesn't affect the playable property which is related to having enough mana)
- changed the draw_cards() method in the PlayerHandler, so we can re-enable after drawing a bunch of cards.
- 
However, this introduces a new bug:
The card doesn't pick up the mouse_entered until it's not enabled. So if I position the mouse where a card ends up after the drawing process in won't appear as hovered. You would need to slightly move the mouse. To avoid this I changed card_ui.gd and hand.gd:
- we check if the card is hovered with a rect and get_local_mouse_position()
