### ISSUE TITLE
Boss condition action doesn't cast 2nd time if you damage through its HP threshold on the first turn

### ISSUE THREAD

**Issue by stefan-zdravkovic** [guladam/deck_builder_tutorial#24]
If Toxic Ghost manages to take enough damage on its first turn to get below the HP threshold, the 2nd muscle buff action won't be performed at all in the fight.

Quick fix I found:

In toxic_ghost_muscle_buff_action.gd script, move the 
`usages += 1`
from `is_performable()` to `perform_action()` method.

This way the `usages` variable only gets updated when action is complete instead of it updating every time the boss takes damage (since that's when `is_performable` is typically being called)

**Comment by guladam** [comment]
Hey, thanks for submitting you are right.
Your fix is probably the easiest, quickest and cleanest one!
