### ISSUE TITLE
Status use the same resource if target is not single_targeted.May be the other problem of duplicate(true)?

### ISSUE THREAD

**Issue by KuroNekqaq** [guladam/deck_builder_tutorial#25]
I try to make a new card that could add_status to every enemy.(or you could change the card: warrior_big_slam's target to all enemies)

But then I found that, when turn over,if there is 2 enemies get exposed,their exposed's duration would decrease 2 and for 2 times.

And if you use 2 warrior_big_slam to 2 different enemy,it works well without problems.

I'm almost sure this is another one problem of duplicate(true),so i try to fix it.

to fix it:

in status_effect.gd:
after the line:
if target is Enemy or target is Player:

add:
var new_status := Status.new(),
new_status = status.duplicate()

and change target.status_handler.add_status(status) to target.status_handler.add_status(new_status).

I wonder if there's a better way to fix it. I'm really bad at it><

**Comment by guladam** [comment]
Hey, thanks for submitting. 

You are right, this is a bug but it has nothing to do with the engine it was an oversight on my end.
If you don't duplicate the status resources the will be shared between multiple targets. Changing the code in StatusEffect fixes it really easily. We just duplicate the Resource for all the targets.

**Comment by UncannyCritter** [comment]
Yeeeeessss!!! Thank you!! I've been wondering if I missed something, looking back through the videos, finding nothing. Thanks so much @KuroNekqaq and @guladam

**Comment by guladam** [comment]
Glad it helped you too :) that's why I encouraged people to open issues because things like these easily get lost in the YouTube comment section. 😅
