### ISSUE TITLE
Starting point can be chosen multiple times by _get_random_starting_points

### ISSUE THREAD

**Issue by Darkwater2k** [guladam/deck_builder_tutorial#26]
In the func _get_random_starting_points in the map generator, the resulting array can have multiples of the same starting point.
e.g. from my print: [4, 0, 0, 4, 2, 5]
Because of this 4 starting points can branch into 5 nodes as seen in the map generator video at 1:47:18

probably enough to pull y_coordinates.append(starting_point) into the "if not y_coordinates"

**Comment by Darkwater2k** [comment]
Hm actually just noticed that this is the same in SlayTheSpire, so maybe not a bug, but a feature? :)

**Comment by guladam** [comment]
Hey, yeah it works the same way. 

The number of starting points does not equal to the number of branching paths. I'll close this for now if you don't mind. :)
