### ISSUE TITLE
Card_pile_view:_update_view method randomized parameter should not rely on RNG.instance

### ISSUE THREAD

**Issue by tyrtheexile** [guladam/deck_builder_tutorial#30]
The _update_view method is called each time it is clicked, and can be used to manipulate the RNG.instance state in the middle of a battle. In theory a player could use this to change intents and/or gold rewards.

**Comment by guladam** [comment]
That's a very nice catch, it can indeed be a source of outcome manipulation. 

Fortunately, the fix is pretty simple.
We can use the built-in RNG instance instead of the seed-based one to shuffle the draw pile.
