### ISSUE TITLE
During a battle with 2 or more enemies, if the player is defeated by the final enemy, the game will crash on the start of the next player turn

### ISSUE THREAD

**Issue by n1mrod88** [guladam/deck_builder_tutorial#8]
The issue I see: Invalid index "status_handler" on base "Nil" (previously freed instance)

This is the line the problem occurs at (player_handler.gd's start_turn function):

player.status_handeler.apply_statuses_by_type(Status.Type.START_OF_TURN)

(ignore the spelling mistake above, this is how I named my status handler in the code)

**Comment by n1mrod88** [comment]
My solution to the problem:

Only trigger start of turn effects for the player if they start the turn with 1 or more HP

**Comment by guladam** [comment]
I couldn't reproduce this issue. If the last enemy kills me the game instantly freezes and goes to the game over state. Can you tell me ways to reproduce this?

**Comment by n1mrod88** [comment]
I honestly don't remember how did I trigger this bug.
